- packages/backend/index.ts
- packages/backend/src/configuration/__mocks__/discord.ts
- packages/backend/src/configuration/__mocks__/environment.ts
- packages/backend/tests/auth.spec.ts
In diesen Änderungen habe ich manuelle Mocks für die Dateien `\packages\backend\src\configuration\discord.ts` und `\packages\backend\src\configuration\environment.ts` hinzugefügt. So sollte es bei Unit-Tests einfacher sein diese Imports ohne weiteren Aufwand zu 'mocken'.
> Unit Tests 1

- packages/backend/src/controllers/authentication/auth.ts
- packages/backend/src/routes/authentication.routes.ts
- packages/backend/tests/auth.spec.ts
- packages/frontend/src/App.vue
- packages/frontend/src/store/index.js
- packages/frontend/src/store/utils/StoreUtil.js
- packages/frontend/src/views/Login.vue
- packages/frontend/tests/unit/login.view.spec.js
Mit diesen Änderungen habe die Implementierung der JWTs im Frontend verbessert.
**Verbesserungen**
- Token wird nach erfolgreicher Verwendung gelöscht.
- Im Frontend wird der JWT im localStorage gespeichert, sodass auch nach einem Neuladen der Seite der Zugang bestehen bleibt. 
- Wenn der Token abgelaufen ist, wird der User zum Login weitergeleitet.
- Wenn ein gültiger Token vorhanden ist, wird der User zum Dashboard weitergeleitet.
> Improve authentification using jwt

- packages/backend/index.ts
- packages/backend/src/controllers/refreshRate/refreshRate.schema.ts
- packages/backend/src/controllers/refreshRate/refreshRate.ts
- packages/backend/src/routes/index.routes.ts
- packages/backend/src/routes/settings.routes.ts
- packages/frontend/src/components/RefreshRateInput.vue
- packages/frontend/src/router/index.js
- packages/frontend/src/store/index.js
- packages/frontend/src/views/Dashboard.vue
> **Als ein** Admin
**möchte ich** das Aktualisierungsintervall in der Web-GUI ändern
**weil** die Informationen aktueller oder gebündelter kommen sollen.
Dieser branch umfasst die Implementierung von Methoden zur Verwaltung der
Aktualisierungsrate mit der die Moodle-Daten abgerufen werden. Zusätzlich
außerdem die Implementierung eines Eingabefeldes im Web-Dashboard mit der benötigten API-Middleware.
- Aktualisierungsintervall als Parameter
- Speichern des Initialwertes in der Datenbank und Rafctoring bestehenden Codes
- Schreiben in die Datenbank
- Returnwert als Erfolgsstatus (HTTP)
- Logging von eventuellen Fehlern
- Prüfung auf gültige Werte
- Einbindung in die Web-GUI
> Set moodle refresh rate

- packages/frontend/src/App.vue
- packages/frontend/src/components/NavBar.vue
- packages/frontend/src/router/index.js
- packages/frontend/src/store/index.js
- packages/frontend/src/views/Dashboard.vue
- packages/frontend/tests/unit/dashboard.view.spec.js
- packages/frontend/tests/unit/navbar.spec.js
**Als ein** Admin
**möchte ich** mich von der WebGui abmelden
**weil** fertig bin und die Session aus Sicherheitsgründen beenden möchte.
Diese Branche beinhaltet die Implementierung des Logout-Features.
- Verknüpfung mit Abmelden Button auf Web-Gui
- Entfernung der aktiven Session
- Logging von eventuellen Fehlern
- Weiterleitung des Nutzers auf die Anmeldeseite
- Das Dashboard soll nur angemeldet erreichbar sein
- Erneutes Anmelden eines Nutzers
> Logout Method

- packages/backend/package-lock.json
- packages/backend/src/controllers/courseList/courseList.schema.ts
- packages/backend/src/controllers/courseList/courseList.ts
- packages/backend/src/controllers/moodle/index.ts
- packages/backend/src/routes/settings.routes.ts
- packages/frontend/src/components/CourseSelection.vue
- packages/frontend/src/store/index.js
- packages/frontend/src/views/Dashboard.vue
> **Als ein** Admin
**möchte ich** die Kursauswahl der Web-GUI ändern
**weil** ich an manchen Kursbenachrichtigungen nicht interessiert bin.
Dieser branch umfasst die Implementierung von folgenden Methoden:
- Methode welche alle Kurse zurückgibt
- Methode welche eine Blacklist der Kurse zurückgibt für die keine Benachrichtigungen erfolgen sollen
- Methode welche einen Kurs auf die Blacklist setzt bzw. entfernt
- Frontend-Komponente und erforderliche API-Middleware
Zusätzlich etwas refactoring von bestehendem Code wo notwendig.
- Kursname und Aktivierungswert (True/False) als Parameter
- Schreiben in die Datenbank
- Returnwert als Erfolgsstatuss (HTTP)
- Logging von eventuellen Fehlern
- Prüfung auf gültige Werte
- Einbindung in die Web-GUI
> Set course list

- README.md
- packages/backend/src/configuration/environment.ts
- packages/backend/src/controllers/discord/index.ts
- packages/backend/src/controllers/discordChannel/discordChannel.schema.ts
- packages/backend/src/controllers/discordChannel/discordChannel.ts
- packages/backend/src/routes/settings.routes.ts
- packages/frontend/src/components/DiscordChannelInput.vue
- packages/frontend/src/store/index.js
- packages/frontend/src/views/Dashboard.vue
> **Als ein** Admin
**möchte ich** den Discord-Channel der Web-GUI ändern
**weil** die Benachrichtigungen in einem anderen Channel ankommen sollen.
Dieser branch umfasst die Implementierung von Methoden zur Verwaltung der
des Discord-Channels zu welchem der Bot Nachrichten sendet.
Zusätzlich außerdem die Implementierung eines Eingabefeldes im Web-Dashboard
mit der benötigten API-Middleware.
Code refactoring wo netwendig.
- Channel-ID als Parameter
- Schreiben in die Datenbank
- Returnwert als Erfolgsstatus (HTTP)
- Logging von eventuellen Fehlern
- Prüfung auf gültige Werte (Channel)
- Einbindung in die Web-GUI
- .env-Varaible entfernen
> Set discord channel

- packages/backend/src/controllers/moodle/fetch.ts
- packages/backend/src/controllers/moodle/handle.ts
- packages/backend/src/controllers/moodle/index.ts
- packages/backend/tests/moodle.handle.spec.ts
- packages/backend/tests/moodle.spec.ts
- packages/frontend/vue.config.js
Added ability to fetch moodle ressources from within subdirectories. Affected unit tests have been updated. Also vue.config has been added, frontend can now be called via domain instead of ip only
> Fix moodle fetch

- packages/backend/src/docs/rest-api.yml
API Dokumentation hinzugefügt für:
- GET /api/refreshRate
- PUT /api/refreshRate
- GET /api/courses
- PUT /api/courses/:id
- GET /api/discordChannel
- PUT /api/discordChannel
> :twisted_rightwards_arrows: Added api documentation (#2)

- .github/workflows/node.js.yml
- packages/backend/src/controllers/authentication/auth.ts
- packages/frontend/package-lock.json
- packages/frontend/package.json
- packages/frontend/public/index.html
- packages/frontend/src/main.js
- packages/frontend/src/store/index.js
- packages/frontend/src/store/utils/StoreUtil.js
- packages/frontend/src/views/Login.vue
- packages/frontend/tests/unit/login.view.spec.js
Neues Aussehen für die Anmeldung verfügbar 🎉 Folgende Punkte haben sich geändert:
- Neues Aussehen in der Login.vue
- Bulma über Buefy eingebunden ( ⚠️ Ist nicht immer up to date mit dem Original)
- Fehlermeldungen als [Buefy-Notification](https://buefy.org/documentation/notification/)
- Fehlermeldungen müssen an den Store als _new Error('...')_ weitergegeben werden.
Foto ist im Issue #32 verfügbar
Closes #32
> 🎨 Bulma CSS für die Anmeldung

- packages/backend/index.ts
- packages/backend/src/controllers/moodle/index.ts
Changed function setInterval to setTimeout to check for new refreshRate before calling fetchAndNotify.
Fixes #38.
> Fixed ignored refreshRate modifications

- packages/frontend/src/App.vue
- packages/frontend/src/store/index.js
- packages/frontend/src/views/Login.vue
- packages/frontend/tests/unit/views/login.view.spec.js
> 🐛 Fixes #42 and #21

- docs/index.html
- docs/main.js
> **Als ein** Benutzer
> **will ich** unter fmdb.tjarbo.me einen Fehler bekommen, wenn die Moodle-Schnittstelle nicht funktioniert
> **weil** der Bot in seinem Webinterface noch keine ausreichenden Informationen bereitstellt.
Ich gehe mal direkt in die `master` branch, da diese Änderungen nur https://fmdb.tjarbo.me betreffen und diese nur in der `master`-branch deployed werden.
Fixes #68
> ✨ Überprüfung der Moodle-API unter fmdb.tjarbo.me

- .devcontainer/Dockerfile
- packages/backend/src/controllers/authentication/auth.ts
- packages/backend/src/controllers/discord/index.ts
- packages/backend/src/utils/api/middleware.ts
- packages/backend/tests/api.middleware.spec.ts
- packages/backend/tests/auth.spec.ts
Fixes #77, so now the user will receive an error message if the token delivery fails. The error will be logged, too.
> 🐛 Fixes #77

- packages/backend/src/configuration/environment.ts
- packages/backend/src/controllers/authentication/auth.ts
- packages/backend/tests/auth.spec.ts
- packages/frontend/src/views/Login.vue
> **As a** developer
> **I want** to use the same regex to validate the discord username 
> **to** prevent unexpected behaviors of the application
Closes #64 
With this PR I adjust the used regex to validate the discord username. I added a character limitation for the part _before the #_ according to this [Discord-Developer article](https://discord.com/developers/docs/resources/user#usernames-and-nicknames).
> 🐛 Einheitliches RegExp - Closes #64

- .github/ISSUE_TEMPLATE/user-story.md
- .github/workflows/cd.main.yml
- .github/workflows/cd.release.yml
- .github/workflows/ci.yml
This PR should fix #93 where the CD is unable to build the Docker Image. It's caused by the default `context` which was the Repo URL instead of the local codebase of the (actions) container
> 🐛  Fixes #93

- packages/backend/src/controllers/moodle/handle.ts
- packages/backend/tests/moodle.handle.spec.ts
> 🔀 Provide default value for timestamp. Fixes #60

- README.md
> 📝 Updated README - Fixes #107

- .github/workflows/ci.yml
Normally #132 should run a Static Application Security Test. Unfortunately, it did not work :confused:. 
This PR should fix this.
> 💚 Fixed CI SAST jobs

- packages/backend/src/controllers/connectors/handlers.ts
- packages/backend/src/controllers/connectors/plugins/connectorPlugin.class.ts
- packages/backend/src/controllers/connectors/plugins/discordBot.class.ts
- packages/backend/src/controllers/connectors/service.ts
- packages/backend/src/routes/connectors.routes.ts
- packages/frontend/src/components/connectors/ConnectorPanel.vue
- packages/frontend/src/components/connectors/sockets/DiscordSocket.vue
- packages/frontend/src/store/modules/connectors.js
> **As a** user
> **I want** want to change the configuration of a connector 
> **because** e.g the discord channel changed
Close #145 
With this user story the user is now able to update connector settings via the frontend. The following attributes can be changed:
* `active` - Defines if a connector will be able to send messages
* `default` - Defines if a connector will be used if no connector has been found based on the related courses
* `socket` - Depends on the connector type - For Discord Bot it is `token` and `channel`
> Update a connector

- packages/backend/src/controllers/connectors/handlers.ts
- packages/backend/src/controllers/connectors/plugins/connectorPlugin.class.ts
- packages/backend/src/controllers/connectors/plugins/discordBot.class.ts
- packages/backend/src/controllers/connectors/service.ts
- packages/backend/src/routes/connectors.routes.ts
- packages/frontend/src/components/connectors/ConnectorPanel.vue
- packages/frontend/src/store/modules/connectors.js
> **As a** user
> **I want** delete a connector
> **because** I do not use the platform anymore
Closes #146 
Now a user is able to delete a connector :grinning:
> Delete a connector
